# Updated to new Version with Python 3
wiejakp/python-sitemap-generator pull request #3
Opened 2020-04-22 19:47 UTC by chainstair

2020-05-01 21:23 UTC, wiejakp commented
@chainstair, thank you for the update. Your changes look good and I'll include them in next release.

2021-12-22 07:36 UTC, wiejakp requested changes
2 things, you left out debugging message and  bug in your repo is true.

though can't merge repo as is, i will be using your code for v0.4.

my apologies not sure how to make a fast update to a pr from another repo :)

2021-12-22 07:38 UTC, wiejakp requested changes

2021-12-22 07:38 UTC, wiejakp commented on python-sitemap-generator.py
> +InitialURL = 'http://test.at/'
change isn't needed

2021-12-22 07:38 UTC, wiejakp commented on python-sitemap-generator.py
> +# Updated to new Version with Python 3
change should go in changelog instead.

2021-12-22 07:40 UTC, merged

2021-12-22 07:44 UTC, chainstair commented
You r welcome to use my code :)

Best regards
chainstair